# Generated by Django 3.2.16 on 2023-01-05 21:18

from django.db import migrations

def capitalise(apps, schema_editor):
    Product = apps.get_model('main', 'Product')
    for product in Product.object.all():
        product.name = product.name.capitalize()
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_managers'),
    ]

    operations = [
        migrations.RunPython(
            capitalise,
            migrations.RunPython.noop
        ),
    ]
