# Generated by Django 4.1.4 on 2023-01-14 21:47

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productname_capitalise'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='producttag',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.producttag'),
        ),
    ]
